### PR TITLE
final commit test tictactoe

### PR DESCRIPTION
**Pull request by henriqueflores12**
## Checkpoint Rubric
This is the rubric that your instructor will use to grade your checkpoints. Please do not edit. 

**Checkpoint 1**
- [ ] All tests passed: 40 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] Properly indented code: 15 points
- [ ] Demonstrated effective use of JavaScript: 30 points

**Checkpoint 2**
- [ ] The application works as it should: 40 points
- [ ] Proper use of documentation (commenting on code): 15 points
- [ ] Properly indented code: 15 points
- [ ] Demonstrated effective use of JavaScript and the DOM API: 30 points

**Checkpoint 3**
- [ ] Use of React: 25 points
- [ ] Accesses an API: 25 points
- [ ] Proper use of documentation (commenting on code): 25 points
- [ ] The application functions as it should: 25 points

### CODE REVIEW

**Comment by henriqueflores12** [comment]
sorry i commit two the same branch i will work on this ok just so you know

**Comment by henriqueflores12** [comment]
two project in the same breach tictactoe and piglatin ok

**Comment by DinhH** [comment]
I like the way you did the pig latin.

**Comment by DinhH** [comment]
TTT looks good so far

**Comment by henriqueflores12** [comment]
😟sorry if it wasn’t like you spect 😰
I promise I will work harder I know I need to improve so much I feel like when I talk to you I feel like I did not born yet in coding you are so good and cunning in coding that scares me 😟
I try a million times and think before talk with you about anything because I don’t want to sound more idiotic then I am 😰😟😥😥sorry

Henrique flores
5128769211
Henriquefagner@hotmail.com<mailto:Henriquefagner@hotmail.com>
F.henrique.flores@gmail.com<mailto:F.henrique.flores@gmail.com>
Thanks for letting me know I promise you
I will try harder ok 😥

On Jul 7, 2019, at 5:44 PM, Dinh Huynh <notifications@github.com<mailto:notifications@github.com>> wrote:


I like the way you did the pig latin.

**Pull request merged**
